import { Inter } from 'next/font/google'
import BodyStyle from "./bodystyle.module.css";
import './globals.css'
import Provider from '@/components/Providers';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={BodyStyle.body}>
        <Provider>
            {children}
        </Provider>
      </body>
    </html>
  )
}
